### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by dw9694** [dw9694/vim-translate#1]
Error occurs when trying to translate text.
```
Traceback (most recent call last):                                                                                                                                                             
  File "<stdin>", line 1, in <module>                                                                                                                                                          
  File "/home/dw/.local/lib/python3.8/site-packages/googletrans/client.py", line 182, in transl                                                                                                
ate                                                                                                                                                                                            
    data = self._translate(text, dest, src, kwargs)                                                                                                                                            
  File "/home/dw/.local/lib/python3.8/site-packages/googletrans/client.py", line 78, in _transl                                                                                                
ate                                                                                                                                                                                            
    token = self.token_acquirer.do(text)                                                                                                                                                       
  File "/home/dw/.local/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do                                                                                                    
    self._update()                                                                                                                                                                             
  File "/home/dw/.local/lib/python3.8/site-packages/googletrans/gtoken.py", line 62, in _update                                                                                                
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')                                                                                                                             
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by dw9694** [comment]
Apparently it's a recent and widespread problem on Google's side. Quoting various Github discussions, it happens when Google sends you directly the raw token.

It's being discussed right now and there is already a pull request to fix it, so it should be resolved in the next few days.

https://stackoverflow.com/a/52885859

`pip install googletrans-temp`

**Comment by dw9694** [comment]
works, but every other time. I'll leave it as it is for now.
